"""empty message

Revision ID: 09926e9b64f9
Revises: 90f887e7c724
Create Date: 2021-02-18 11:32:00.314792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09926e9b64f9'
down_revision = '90f887e7c724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
