"""empty message

Revision ID: 482eb356c594
Revises: 64e7382729cd
Create Date: 2021-02-18 14:56:38.534212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482eb356c594'
down_revision = '64e7382729cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
